FROM node:alpine

WORKDIR /work

RUN apk add --no-cache bash curl git py-pip openssl alpine-sdk python-dev zip

RUN pip install --upgrade awscli

RUN pip install --upgrade aws-sam-cli

ADD . .

CMD S3_BUCKET=${LAMBCI_DEPLOYMENT_BUCKET:-lambci} npm run deploy