FROM node:alpine

WORKDIR /work

RUN apk add --no-cache bash curl git py-pip openssl alpine-sdk python-dev

RUN pip install --user aws-sam-cli

ADD . .

CMD S3_BUCKET=${LAMBCI_DEPLOYMENT_BUCKET:-lambci} npm run deploy